### ISSUE TITLE
Question about damfile_pb2

### ISSUE THREAD

**Issue by mikhoul** [willowpsychology/rogue_matterport_archiver#1]
I try to convert a dam file I have to OBJ but When I run the command I receive an error that the module damfile_pb2 is missing.

![image](https://user-images.githubusercontent.com/5678673/187510054-0e51bbbc-bd3d-4908-9219-14f6cb4acbbe.png)

Where I can find this module ? :thinking: 

NB: I see that @maddigit forked the repo maybe you can help me too. 

Regards ! :octocat:

**Comment by willowpsychology** [comment]
The file damfile_pb2.py needs to be generated first. Try:
`protoc --python_out=. damfile.proto`
If you get a error like "protoc: command not found" try this instead:
```
pip install grpcio-tools
python -m grpc_tools.protoc -I . --python_out=. damfile.proto
```

**Comment by mikhoul** [comment]
Thanks a lot for the help, I will try it. :+1:

**Comment by mikhoul** [comment]
@willowpsychology  It seem to have worked :smile: , one last question you are saying "_Any texture images need to be copied to the output directory_"

In what folder/directory are the picture ?  :thinking: 

My guess it is in the asset folder within the directory ending by ...__50k_texture_jpg_high_ and ...__50k_texture_jpg_low_ but I'm not sure.

![image](https://user-images.githubusercontent.com/5678673/188223793-b072a2e8-2a31-4e12-977d-735d6031b42a.png)

My output folder where the OBJ file is is "_OBJ_dollhouse_" so I don't know if I put only the files (JPG texture files) of the complete folder directory under the "_assets_" folder ?

Does I use the "_tiles_" folder too ?

Thanks a lot for your help. :octocat:

**Comment by willowpsychology** [comment]
You should copy the contents of "..._50k_texture_jpg_high" or "..._50k_texture_jpg_low" (but not both) into "OBJ_dollhouse"

The generated .mtl file has a list of texture filenames that it expects. You can check that to verify.

My example directory structure looks like this:
```
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004.obj
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004.mtl
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004_50k_000.jpg
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004_50k_001.jpg
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004_50k_002.jpg
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004_50k_003.jpg
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004_50k_004.jpg
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004_50k_005.jpg
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004_50k_006.jpg
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004_50k_007.jpg
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004_50k_008.jpg
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004_50k_009.jpg
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004_50k_010.jpg
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004_50k_011.jpg
8800BLR_dollhouse/da1a5ccd99d044f586788232864f0004_50k_012.jpg
```

The start of "da1a5ccd99d044f586788232864f0004.mtl" looks like this:
```
newmtl da1a5ccd99d044f586788232864f0004_50k_000.jpg
map_Ka da1a5ccd99d044f586788232864f0004_50k_000.jpg
map_Kd da1a5ccd99d044f586788232864f0004_50k_000.jpg

newmtl da1a5ccd99d044f586788232864f0004_50k_001.jpg
map_Ka da1a5ccd99d044f586788232864f0004_50k_001.jpg
map_Kd da1a5ccd99d044f586788232864f0004_50k_001.jpg
```

**Comment by mikhoul** [comment]
Thanks a lot for the help ! :+1:
